POST  http://localhost:5124/tora/Auth/register HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNTgwYzk0NS01MTEzLTRlN2YtYWQ4NS1mMmQzZDZlN2Y4MjMiLCJlbWFpbCI6InN1cGVyYWRtaW5AdG9yYS5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImU1ODBjOTQ1LTUxMTMtNGU3Zi1hZDg1LWYyZDNkNmU3ZjgyMyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InN1cGVyYWRtaW5AdG9yYS5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJTdXBlckFkbWluIiwianRpIjoiZWIxNTBjNGYtNjdiMS00YWE1LThiYjMtMmYyNzcxYTVkZWE1IiwiZXhwIjoxNzc1NDI4NDAzLCJpc3MiOiJUb3JhQXBpIiwiYXVkIjoiVG9yYUFwaVVzZXJzIn0.u3yapRfIh6Jgh03MYctJYIlQOc5nRXkVw_ZNJga5fRE

{
    "name": "testuser",
    "email": "testuser@example.com",
    "password": "password456"
}
###

POST  http://localhost:5124/tora/Auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "superadmin@tora.com",
    "password": "SuperAdmin@12345"
}